language: node_js

node_js:
  - "10"

script:
  - npm run test
  - npm run build

deploy:
  provider: netlify
  site: 18ef0b6b-42bb-4de9-8f24-b97e131d119a
  auth: 0aa695bf5d4e8337c3664ac8028ec0f0be459845afef140079a6112b75237f63
  dir: public
  prod: true
  edge: true
